codecov:
  branch: main
  require_ci_to_pass: true

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: yes
  require_head: yes
  branches: null

# new section in the root YAML, flag_management:
flag_management:
  # this section will govern all default rules of Flags
  default_rules:
    carryforward: false
