version: '3.7'
services:
  ganache:
    container_name: ganache
    image: trufflesuite/ganache:latest
    ports:
      - "8545:8545"
    command:
      - --database.dbPath=/ganache_data
      - --wallet.mnemonic
      - 'minimum symptom minute gloom tragic situate silver mechanic salad amused elite beef'
      - --chain.networkId
      - '5777'
      - --server.host
      - '0.0.0.0'
      - --logging.debug
      - --wallet.totalAccounts
      - '100'
  flextesa:
    container_name: flextesa
    image: tqtezos/flextesa:20210602
    ports:
      - "20000:20000"
    command: flobox start
