extends: "../../../.nycrc.yml"
exclude:
  - "packages/cast/utils/**/*.spec.ts"
include:
  - "packages/cast/utils/src/**/*.ts"
extension:
  - ".ts"
cwd: "../../../"
report-dir: "reports/coverage/ut-utils"
