extends: "../../../.nycrc.yml"
exclude:
  - "packages/cast/transaction-manager/**/*.spec.ts"
include:
  - "packages/cast/transaction-manager/src/**/*.ts"
extension:
  - ".ts"
cwd: "../../../"
report-dir: "reports/coverage/ut-transaction-manager"
