extends: "../../../.nycrc.yml"
exclude:
  - "packages/cast/blockchain-driver-tz/**/*.spec.ts"
include:
  - "packages/cast/blockchain-driver-tz/src/**/*.ts"
extension:
  - ".ts"
cwd: "../../../"
report-dir: "reports/coverage/ut-blockchain-driver-tz"
