name: Pre-Release(Retry Publish)
on: workflow_dispatch

jobs:
  tests:
    name: Unit test (Node ${{ matrix.node }}, ${{ matrix.architecture }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["16"]
        architecture: ["x64"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          architecture: ${{ matrix.architecture }}
          cache: "npm"

      - name: Install
        run: |
          npm install -g npm lerna
          npm ci
          ./bin/symlink-bin
          lerna link
      - name: Build
        run: |
          lerna run build
      - name: Lint
        run: |
          lerna run lint
      - name: Test
        run: |
          lerna run stats
      - name: Upload code coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./reports/coverage/ut-transaction-manager/cobertura-coverage.xml,./reports/coverage/ut-blockchain-driver-eth/cobertura-coverage.xml,./reports/coverage/ut-blockchain-driver-tz/cobertura-coverage.xml,./reports/coverage/ut-types/cobertura-coverage.xml,./reports/coverage/ut-utils/cobertura-coverage.xml
          flags: unit
          name: codecov-umbrella
          verbose: true
        if: ${{ matrix.node == '16' && matrix.architecture == 'x64' }}

      - name: Authenticate with Registry
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
          npm whoami
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        if: ${{ matrix.node == '16' && matrix.architecture == 'x64' }}

      - name: Setup git
        run: |
          git config --global user.email "ci@github.com"
          git config --global user.name "CI"
        if: ${{ matrix.node == '16' && matrix.architecture == 'x64' }}

  integration-tests:
    name: Integration tests (Node ${{ matrix.node }}, ${{ matrix.architecture }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["16"]
        architecture: ["x64"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          architecture: ${{ matrix.architecture }}
          cache: "npm"

      - name: Install
        run: |
          npm install -g npm lerna
          npm ci
          ./bin/symlink-bin
          lerna link
      - name: Start blockchains
        run: |
          docker-compose up -d
          docker-compose ps
      - name: Setup blockchains
        run: |
          ./bin/iter-all
      - name: Instrument code
        run: |
          lerna run instrument
          lerna run build
          git status
          git reset --hard
      - name: Integration tests
        run: |
          lerna run stats:integration
      - name: Upload code coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./reports/coverage/it-testing/cobertura-coverage.xml
          flags: integration
          name: codecov-umbrella
          verbose: true

      - name: Stop blockchains
        run: docker-compose down

  publish:
    needs:
      - tests
      - integration-tests
    name: Publish (Node ${{ matrix.node }}, ${{ matrix.architecture }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["16"]
        architecture: ["x64"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          architecture: ${{ matrix.architecture }}
          cache: "npm"

      - name: Install
        run: |
          npm install -g npm lerna
          npm ci
          ./bin/symlink-bin
          lerna link
      - name: Build
        run: |
          lerna run build
      - name: Authenticate with Registry
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
          npm whoami
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Setup git
        run: |
          git config --global user.email "ci@github.com"
          git config --global user.name "CI"
      - name: Publish packages
        run: |
          lerna publish from-package --yes --no-verify-access --dist-tag next
        if: ${{ matrix.node == '16'  && matrix.architecture == 'x64' }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ github.token }}
